name: ansible-playbook  # ワークフローの名前
# トリガー この例では、全てのブランチにおけるpushでキックされる。
# See https://docs.github.com/ja/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
on:
  push:
    paths:
      - 'Ansible/**'
      - '.github/workflows/ansible-playbook.yml'
jobs:
  ansible-playbook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ansible playbook
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 700 ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -p 22 -H 164.70.121.236 >> ~/.ssh/known_hosts  # manager001.ga
        ssh-keyscan -p 22 -H 164.70.76.72 >> ~/.ssh/known_hosts  # staging001.ga
        # ssh-keyscan -p 22 -H 164.70.65.194 >> ~/.ssh/known_hosts  # test003.ga
        # ssh-keyscan -p 22 -H 164.70.70.140 >> ~/.ssh/known_hosts  # test004.ga
        # ssh-keyscan -p 22 -H 164.70.90.222 >> ~/.ssh/known_hosts  # test005.ga
        # ssh-keyscan -p 22 -H 164.70.114.195 >> ~/.ssh/known_hosts  # production001.ga
        cd Ansible/
        ansible-playbook -i inventory/hosts.yml playbooks/site.yml --private-key ~/.ssh/id_rsa
