all:
  children:
    linux:
      children:
        pukiwiki:
        # kubernetes:
        staging:
        production:
        ansible:
        zabbix_server:
        zabbix_agent:
    zabbix_agent:
      children:
        pukiwiki:
        ansible:
        # kubernetes:
        staging:
        production:
    ansible:
      hosts:
        ansible1.ga:
    pukiwiki:
      hosts:
        pukiwiki.ga:
    staging:
      hosts:
        staging001.ga:
    production:
      hosts:
        production001.ga:
    zabbix_server:
      hosts:
        zabbix001.ga:
