- include_tasks: tasks/check.yml

- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: set timezone
  timezone:
    name: "{{ vars.timezone }}"

- name: Install Zabbix Repo
  yum:
    name: "{{repo_url}}"
    state: present
    disable_gpg_check: yes
