- name: Docker Deploy
  hosts: "{{ docker_deploy_host }}"
  become: true
  gather_facts: true

  tasks:
    - name: Dockerで使うホスト側のport開放
      firewalld:
        port: "{{docker_host_port}}"
        permanent: no # 再起動すると閉じるport
        state: enabled

  roles:
    - role: docker_image_prune
      tags: docker_image_prune

    - role: docker_container_stop
      tags: docker_container_stop

    - role: docker_container_prune
      tags: docker_container_prune

    - role: docker_pull_image
      tags: docker_pull_image

    - role: docker_container_run
      tags: docker_container_run
