- name: Docker Deploy
  hosts: "{{ docker_deploy_host }}"
  become: true
  gather_facts: true

  vars:
    docker_host_port: "{{ docker_host_port }}"
    docker_container_port: "{{ docker_container_port }}"
    docker_image: "{{ docker_image }}"

  roles:
    - role: docker_pull_image
      tags: docker_pull_image

    - role: docker_container_run
      tags: docker_container_run
