# Linux共通用のPlaybook
# Playbook用の設定
# 前提としては、Ansibleユーザが設定されている状態（それ以外は全く設定されていない）
---
- name: Linuxの共通設定用のPlaybook
  hosts: linux
  become: true
  gather_facts: true

  roles:
    # ホスト名変更
    - role: change_hostname
      tags: change_hostname

    # 共通パッケージインストール
    - role: linux_common_packages
      tags: linux_common_packages

    # firewalld有効化と設定
    - role: firewalld
      tags: firewalld

    # sshd有効化と設定
    - role: sshd
      tags: sshd

    # dockerインストール
    - role: docker
      tags: docker

    # Zabbixエージェントインストール

    # SELinux 無効化と必要なら再起動
    #- role: selinux
    #  tags: selinux
