---
- name: Prometheus Server
  hosts: prometheus_server
  become: true
  gather_facts: true

  roles:
    - role: prometheus
      tags: prometheus
    - role: firewalld_tcp_port_open
      firewalld_tcp_port: 9090

    - role: node_exporter
      tags: node_exporter
    - role: firewalld_tcp_port_open
      firewalld_tcp_port: 9100

    - role: grafana
      tags: grafana

- name: Prometheus Clients
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: node_exporter
      tags: node_exporter
    - role: firewalld_tcp_port_open
      firewalld_tcp_port: 9100

  tasks:
    - name: Prometheus Serverの設定ファイルに監視対象を追加する
      shell: echo hoge
