# site.ymlはPlaybookの総本山。このPlaybookを流せば必要なInfrastructureが全て揃う状態になるようにトップダウンで設計する。
# 各Playbookをシンプルにimportする記述。
# 各Playbookは、roleをimportする。
# roleに実際の処理を記述する。
# roleにタグ付けを行うことで、局所的なPlaybook適用を可能にする。
---
- name: import linux-common.yml
  import_playbook: linux-common.yml

- name: import manager.yml
  import_playbook: manager.yml

- name: import webapp.yml
  import_playbook: webapp.yml
