---
# tasks file for linux_common_packages
# パッケージインストール
    # httpd, php, wget, vim, phthon39, firewalld
- name: パッケージ インストール
  yum:
    name: "{{ packages }}"
    state: latest

- name: パッケージのアップデート
  shell: yum update -y
  changed_when: false # 結果を常に okにする。
