---
# tasks file for linux_common_packages
# パッケージインストール
    # httpd, php, wget, vim, phthon39, firewalld
- name: パッケージ インストール
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - httpd
    - php
    - wget
    - vim
    - python39
    - firewalld
- name: パッケージのアップデート
  shell: yum update -y
