on:
  push:
    paths:
      - 'Docker/responsive-qiita-header/**'

jobs:
  CICD:
    runs-on: ubuntu-latest
    steps:
      # CI Phase
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
         context: Docker/responsive-qiita-header/
         file:  Docker/responsive-qiita-header/Dockerfile
         push: true
         tags:  ${{ secrets.DOCKER_HUB_USERNAME }}/responsive-qiita-header:latest

      # CD Phase
      - name: deploy docker image
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -p 22 -H 164.70.76.72 >> ~/.ssh/known_hosts  # staging001.ga
          cd Ansible/
          ansible-playbook -i inventory/hosts.yml playbooks/docker-deploy.yml --private-key ~/.ssh/id_rsa --extra-vars 'docker_deploy_host=staging001.ga docker_image="${{ secrets.DOCKER_HUB_USERNAME }}/responsive-qiita-header:latest" docker_host_port=1005 docker_container_port=80 docker_container_name=responsive-qiita-header'
