on:
  push:
    paths:
      - 'Docker/SimpleWebApp/**'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
         context: Docker/SimpleWebApp/
         file:  Docker/SimpleWebApp/Dockerfile
         push: true
         tags:  ${{ secrets.DOCKER_HUB_USERNAME }}/simplewebapp:latest
  CD:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy docker image
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 700 ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -p 22 -H 164.70.76.72 >> ~/.ssh/known_hosts  # staging001.ga
        cd Ansible/
        ansible-playbook -i inventory/hosts.yml playbooks/docker-deploy.yml --private-key ~/.ssh/id_rsa --extra-vars "docker_deploy_host=staging001.ga, docker_image=${{ secrets.DOCKER_HUB_USERNAME }}/simplewebapp:latest, docker_host_port=80, docker_container_port=2000"
        # ansible-playbook -i inventory/hosts.yml playbooks/docker-deploy.yml --private-key ~/.ssh/id_rsa --extra-vars 'docker_deploy_host=staging001.ga, docker_image="${{ secrets.DOCKER_HUB_USERNAME }}/simplewebapp:latest"'
